#!/bin/sh

set -e

if [ "$1" = purge ]; then
    if [ -x /usr/sbin/update-inetd ]; then
	update-inetd --remove sane-port
	update-inetd --remove "#<off># sane-port"
    fi
#
# purge systemd files
#
    rm -f /etc/systemd/system/saned.socket
    rm -f /var/lib/systemd/deb-systemd-helper-enabled/saned.socket.dsh-also
    rm -f /var/lib/systemd/deb-systemd-helper-masked/saned.socket
    if [ -d /var/lib/systemd/deb-systemd-helper-enabled ]; then
        rmdir --ignore-fail-on-non-empty /var/lib/systemd/deb-systemd-helper-enabled
    fi
    if [ -d /var/lib/systemd/deb-systemd-helper-masked ]; then
	rmdir --ignore-fail-on-non-empty /var/lib/systemd/deb-systemd-helper-masked
    fi

fi

#DEBHELPER#
